### ISSUE TITLE
Doc: How to install and use the library 

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/m3ntorship-ui#45]
**Story**
we to add installation & how to use the library 

**Prerequisites**
#9 
#1 
#42 
**Tasks**
Update [README.md](https://github.com/m3ntorship/m3ntorship-ui#readme) so that we have a section showing installation steps and another section showing how to use the library 
**Acceptance criteria**
As a user I should be able  to install & use the library

**Comment by atwfk** [comment]
#97 closes this ticket
