### ISSUE TITLE
Tailwind config for M3ntroship theme

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/m3ntorship-ui#6]
**Story**
we need to add the proper tailwind config to match the tokens as per the design [figam](https://www.figma.com/file/dZ7gP6V7YvjzLimQVrT1sa/Mentorship-DS?node-id=7%3A7004) 

**Prerequisites**
- #2 create project setup 
- #1 integrating tailwindcss

**Tasks**
- After we receive (`to be attached`) json file contains all tokens configuration, use it to generate the proper config 
- we will use helper functions to generate the object values such as `color`, `fontSize`, .... etc.

**Acceptance criteria**
Tailwindcss classes should be generated according to the design.

**Comment by atwfk** [comment]
@elhaw I think the project is ready for this task despite the full project setup task hadn't done yet but you can integrate tailwind and add it's config in parallel
