### ISSUE TITLE
Bugfix/Badge component - Type Error in `children` prop 

### ISSUE THREAD

**Issue by atwfk** [m3ntorship/m3ntorship-ui#88]
**Description**
when I use Badge component and pass children to it, I get type error:
> TypeError: children.charAt is not a function

**How to reproduce**
- import Badge component form `m3ntorship-ui`
```typescript
import { Badge } from 'm3ntorship-ui';
```
- add variable of type string to pass it as children to **Badge** component
```typescript
const name = 'ahmed';
```
- pass the `name` variable and a static string to **Badge** component
```typescript
<Badge>My name is {name}</Badge>
```

**Expected result**
Badge component should render both the static text and variable without issues

**Actual result**
type error appears

**Extras**

![Screenshot from 2022-09-29 19-54-07](https://user-images.githubusercontent.com/52901348/193121033-2e5c40f3-223d-4211-9456-bacd626509e7.png)

**Comment by elhaw** [comment]
The types of `Badge` component is as below
```
export interface IBadgeProps {
  /**Add The text or component which will be wrapped by the Badge component */
  children?: string;
  /**Choose which color variant  for the Badge component*/
  color?: 'primary' | 'secondary' | 'warning' | 'info' | 'error' | 'success';
  /**add additional classes for Badge component */
  className?: string;
}
```
The children props type is `string ` so it should accept only string 
```
//works fine 
 let firstName ='ahmed'
<Badge>{firstName}</Badge> // children value will be   "ahmed"
```

```
//type error as the Badge excepts the children to string but strings array is passed
 let firstName ='ahmed'
<Badge> {first Name} </Badge> // children value will be  ["","ahmed",""]
```

### Demo
check the demo and change the value of children props and it is type and open the dev tools to see the logs
[Badge](https://codesandbox.io/s/react-typescript-forked-czzgnj?file=/src/App.tsx)
### Solution
Better to use `ReactNode` type instead of `string`.
